name = "obsidianbackendhono"
main = "src/index.ts"
compatibility_date = "2025-01-15"

compatibility_flags = ["nodejs_compat"]
# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "clockin"
database_id = "a4f6312b-2078-4212-ac05-b8cb973b08e0"

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
